version: "3.9"
services:

  backend:
    image: 476190904340.dkr.ecr.ap-northeast-2.amazonaws.com/grabit_backend:latest
    port: 8080:8080
    environment:
      - name: SPRING_PROFILES_ACTIVE
        value: local
      - name: SPRING_DATASOURCE_URL
        value: jdbc:mysql://localhost:3306/grabit
      - name: SPRING_DATASOURCE_USERNAME
        value: root
      - name: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
  
  db:
    image: mysql:5.7
    port: 3306:3306
    environment:
      - name: MYSQL_ROOT_PASSWORD
        value: root
      - name: MYSQL_DATABASE
        value: grabit